const getEnvVar = (name: string): string => {
  const value = process.env[name];
  if (!value) {
    throw new Error(`Missing environment variable: ${name}`);
  }
  return value;
};

const API_BASE_URL = getEnvVar("API_BASE_URL");
const API = getEnvVar("API");
const API_VERSION = getEnvVar("API_VERSION");
const USER_ROUTER = getEnvVar("USER_ROUTER");
const USER_ENDPOINT = getEnvVar("USER_ENDPOINT");
const PASSWORD_ENDPOINT = getEnvVar("PASSWORD_ENDPOINT");
const REGISTER_ENDPOINT = getEnvVar("REGISTER_ENDPOINT");
const VERIFY_ENDPOINT = getEnvVar("VERIFY_ENDPOINT");
const VERIFY_TOKEN_ENDPOINT = getEnvVar("VERIFY_TOKEN_ENDPOINT");
const REFRESH_TOKEN_ENDPOINT = getEnvVar("REFRESH_TOKEN_ENDPOINT");
const EMAIL_ENDPOINT = getEnvVar("EMAIL_ENDPOINT");
const LOGIN_ENDPOINT = getEnvVar("LOGIN_ENDPOINT");
const LOGIN_GOOGLE_ENDPOINT = getEnvVar("LOGIN_GOOGLE_ENDPOINT");
const GOOGLE_CLIENT_ID = getEnvVar("GOOGLE_CLIENT_ID");
const LOGOUT_ENDPOINT = getEnvVar("LOGOUT_ENDPOINT");
const DEACTIVATION_ENDPOINT = getEnvVar("DEACTIVATION_ENDPOINT");
const STORAGE_ROUTER = getEnvVar("STORAGE_ROUTER");
const UPLOAD_ENDPOINT = getEnvVar("UPLOAD_ENDPOINT");
const METADATA_ENDPOINT = getEnvVar("METADATA_ENDPOINT");
const DELETE_ENDPOINT = getEnvVar("DELETE_ENDPOINT");
const DOWNLOAD_ENDPOINT = getEnvVar("DOWNLOAD_ENDPOINT");
const DNS_ENDPOINT = getEnvVar("DNS_ENDPOINT");
const DATA_ROUTER = getEnvVar("DATA_ROUTER");
const TEMPLATES_ENDPOINT = getEnvVar("TEMPLATES_ENDPOINT");
const DEACTIVATION_REASONS_ENDPOINT = getEnvVar(
  "DEACTIVATION_REASONS_ENDPOINT"
);
const SUPPORTED_FILES_ENDPOINT = getEnvVar("SUPPORTED_FILES_ENDPOINT");
const FAQ_ENDPOINT = getEnvVar("FAQ_ENDPOINT");
const NEWS_ENDPOINT = getEnvVar("NEWS_ENDPOINT");
const TRANSCRIPT_ROUTER = getEnvVar("TRANSCRIPT_ROUTER");
const TEXT_TO_TXT_ENDPOINT = getEnvVar("TEXT_TO_TXT_ENDPOINT");
const IMG_TO_TXT_ENDPOINT = getEnvVar("IMG_TO_TXT_ENDPOINT");
const AUDIO_TO_TXT_ENDPOINT = getEnvVar("AUDIO_TO_TXT_ENDPOINT");
const VIDEO_TO_TXT_ENDPOINT = getEnvVar("VIDEO_TO_TXT_ENDPOINT");
const AI_ROUTER = getEnvVar("AI_ROUTER");
const TRANSCRIPT_ENDPOINT = getEnvVar("TRANSCRIPT_ENDPOINT");
const PPT_ROUTER = getEnvVar("PPT_ROUTER");
const COUNT_TOKENS_ENDPOINT = getEnvVar("COUNT_TOKENS_ENDPOINT");
const PPT_ENDPOINT = getEnvVar("PPT_ENDPOINT");

export const config = {
  API_BASE_URL,
  API,
  API_VERSION,
  USER_ROUTER,
  USER_ENDPOINT,
  PASSWORD_ENDPOINT,
  REGISTER_ENDPOINT,
  VERIFY_ENDPOINT,
  VERIFY_TOKEN_ENDPOINT,
  REFRESH_TOKEN_ENDPOINT,
  EMAIL_ENDPOINT,
  LOGIN_ENDPOINT,
  LOGIN_GOOGLE_ENDPOINT,
  GOOGLE_CLIENT_ID,
  LOGOUT_ENDPOINT,
  DEACTIVATION_ENDPOINT,
  STORAGE_ROUTER,
  UPLOAD_ENDPOINT,
  METADATA_ENDPOINT,
  DELETE_ENDPOINT,
  DOWNLOAD_ENDPOINT,
  DNS_ENDPOINT,
  DATA_ROUTER,
  TEMPLATES_ENDPOINT,
  DEACTIVATION_REASONS_ENDPOINT,
  SUPPORTED_FILES_ENDPOINT,
  FAQ_ENDPOINT,
  NEWS_ENDPOINT,
  TRANSCRIPT_ENDPOINT,
  TEXT_TO_TXT_ENDPOINT,
  IMG_TO_TXT_ENDPOINT,
  AUDIO_TO_TXT_ENDPOINT,
  VIDEO_TO_TXT_ENDPOINT,
  AI_ROUTER,
  TRANSCRIPT_ROUTER,
  PPT_ROUTER,
  COUNT_TOKENS_ENDPOINT,
  PPT_ENDPOINT,
};
