const getEnvVar = (name: string): string => {
  const value = process.env[name];
  if (!value) {
    throw new Error(`Missing environment variable: ${name}`);
  }
  return value;
};

const API_BASE_URL = getEnvVar("API_BASE_URL");
const API = getEnvVar("API");
const API_VERSION = getEnvVar("API_VERSION");
const USER_ROUTER = getEnvVar("USER_ROUTER");
const USER_ENDPOINT = getEnvVar("USER_ENDPOINT");
const PASSWORD_ENDPOINT = getEnvVar("PASSWORD_ENDPOINT");
const REGISTER_ENDPOINT = getEnvVar("REGISTER_ENDPOINT");
const VERIFY_ENDPOINT = getEnvVar("VERIFY_ENDPOINT");
const TOKEN_ENDPOINT = getEnvVar("TOKEN_ENDPOINT");
const REFRESH_TOKEN_ENDPOINT = getEnvVar("REFRESH_TOKEN_ENDPOINT");
const EMAIL_ENDPOINT = getEnvVar("EMAIL_ENDPOINT");
const LOGIN_ENDPOINT = getEnvVar("LOGIN_ENDPOINT");
const GOOGLE_ENDPOINT = getEnvVar("GOOGLE_ENDPOINT");
const GOOGLE_CLIENT_ID = getEnvVar("GOOGLE_CLIENT_ID");
const LOGOUT_ENDPOINT = getEnvVar("LOGOUT_ENDPOINT");
const DEACTIVATION_ENDPOINT = getEnvVar("DEACTIVATION_ENDPOINT");
const STORAGE_ROUTER = getEnvVar("STORAGE_ROUTER");
const UPLOAD_ENDPOINT = getEnvVar("UPLOAD_ENDPOINT");
const METADATA_ENDPOINT = getEnvVar("METADATA_ENDPOINT");
const TRANSCRIPT_ROUTER = getEnvVar("TRANSCRIPT_ROUTER");
const TEXTTOTXT_ENDPOINT = getEnvVar("TEXTTOTXT_ENDPOINT");
const IMGTOTXT_ENDPOINT = getEnvVar("IMGTOTXT_ENDPOINT");
const AUDIOTOTXT_ENDPOINT = getEnvVar("AUDIOTOTXT_ENDPOINT");
const VIDEOTOTXT_ENDPOINT = getEnvVar("VIDEOTOTXT_ENDPOINT");
const YOUTUBETOTXT_ENDPOINT = getEnvVar("YOUTUBETOTXT_ENDPOINT");
const AI_ROUTER = getEnvVar("AI_ROUTER");
const TRANSCRIPT_ENDPOINT = getEnvVar("TRANSCRIPT_ENDPOINT");
const PPT_ROUTER = getEnvVar("PPT_ROUTER");
const PPT_ENDPOINT = getEnvVar("PPT_ENDPOINT");

export const config = {
  API_BASE_URL,
  API,
  API_VERSION,
  USER_ROUTER,
  USER_ENDPOINT,
  PASSWORD_ENDPOINT,
  REGISTER_ENDPOINT,
  VERIFY_ENDPOINT,
  TOKEN_ENDPOINT,
  REFRESH_TOKEN_ENDPOINT,
  EMAIL_ENDPOINT,
  LOGIN_ENDPOINT,
  GOOGLE_ENDPOINT,
  GOOGLE_CLIENT_ID,
  LOGOUT_ENDPOINT,
  DEACTIVATION_ENDPOINT,
  STORAGE_ROUTER,
  UPLOAD_ENDPOINT,
  METADATA_ENDPOINT,
  TRANSCRIPT_ENDPOINT,
  TEXTTOTXT_ENDPOINT,
  IMGTOTXT_ENDPOINT,
  AUDIOTOTXT_ENDPOINT,
  VIDEOTOTXT_ENDPOINT,
  YOUTUBETOTXT_ENDPOINT,
  AI_ROUTER,
  TRANSCRIPT_ROUTER,
  PPT_ROUTER,
  PPT_ENDPOINT,
};
