"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = __importDefault(require("express"));
const userController_1 = __importDefault(require("./userController"));
const userRouter = express_1.default.Router();
userRouter.post("/register", userController_1.default.registerUser);
userRouter.post("/verify-email", userController_1.default.verifyEmail);
userRouter.post("/login", userController_1.default.loginUser);
userRouter.post("/login-google", userController_1.default.loginUserWithGoogle);
userRouter.post("/logout", userController_1.default.logoutUser);
userRouter.get("/verify-token", userController_1.default.verifyToken);
userRouter.post("/refresh-token", userController_1.default.refreshToken);
userRouter.post("/username", userController_1.default.updateUserName);
userRouter.post("/password", userController_1.default.updatePassword);
userRouter.post("/email", userController_1.default.sendEmail);
userRouter.post("/deactivation", userController_1.default.deactivateAccount);
userRouter.get("/balance", userController_1.default.getCreditBalance);
exports.default = userRouter;
