INSERT INTO supported_files (extension, type, category)
VALUES 
('ppt', 'PowerPoint', 'templates'),
('pptx', 'PowerPoint', 'templates'),
('txt', 'Text', 'media'),
('docs', 'Text', 'media'),
('pdf', 'Text', 'media'),
('png', 'Image', 'media'),
('jpg', 'Image', 'media'),
('jpeg', 'Image', 'media'),
('tiff', 'Image', 'media'),
('gif', 'Image', 'media'),
('bmp', 'Image', 'media'),
('webp', 'Image', 'media'),
('mp4', 'Video', 'media'),
('mpg', 'Video', 'media'),
('mpeg', 'Video', 'media'),
('avi', 'Video', 'media'),
('mov', 'Video', 'media'),
('wmv', 'Video', 'media'),
('mkv', 'Video', 'media'),
('webm', 'Video', 'media'),
('3gp', 'Video', 'media'),
('mp3', 'Audio', 'media'),
('wav', 'Audio', 'media');
