INSERT INTO supported_files (extension, type)
VALUES 
('ppt', 'templates'),
('pptx', 'templates'),
('txt', 'media'),
('docs', 'media'),
('pdf', 'media'),
('png', 'media'),
('jpg', 'media'),
('jpeg', 'media'),
('tiff', 'media'),
('gif', 'media'),
('bmp', 'media'),
('webp', 'media'),
('mp4', 'media'),
('mpg', 'media'),
('mpeg', 'media'),
('avi', 'media'),
('mov', 'media'),
('wmv', 'media'),
('mkv', 'media'),
('webm', 'media'),
('3gp', 'media'),
('mp3', 'media'),
('wav', 'media');
