FROM node:20-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    libreoffice \
    && npm install -g yarn \
    && rm -rf /var/lib/apt/lists/*

COPY . .

RUN yarn install

EXPOSE 3000

CMD ["yarn", "start"]