FROM node:20.9.0-slim

RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    python3-venv \
    build-essential \
    libreoffice \
    ffmpeg && \
    rm -rf /var/lib/apt/lists/* && \
    apt-get clean

RUN python3 -m venv /venv

RUN /venv/bin/pip install --no-cache-dir --upgrade pip && \
    /venv/bin/pip install --no-cache-dir torch openai-whisper numpy==1.24

ENV PATH="/venv/bin:$PATH"

WORKDIR /app
RUN mkdir -p /app/dist/src/upload

COPY package.json yarn.lock ./
RUN yarn install

COPY . .
# COPY ../audioToText.py /app/dist/src/services/transcript/audioToText.py
# COPY src/services/transcript/audioToText.py /app/dist/src/services/transcript/audioToText.py

RUN yarn build

EXPOSE 3000

CMD ["yarn", "start"]