FROM node:20.9.0-alpine

RUN apk update && \
    apk add --no-cache libreoffice python3 py3-pip

WORKDIR /app

RUN mkdir -p /app/dist/src/upload

COPY package.json yarn.lock ./

RUN yarn install

COPY . .

RUN yarn build

EXPOSE 3000

CMD ["yarn", "start"]