import { Request, Response } from "express";
import storageService from "../../services/storage/storageService";
import handleError from "../../utils/common/handleError";
import { config } from "../../../env.config";
import { pool } from "../../db/config/pool";
import { DbQueryResultProps } from "../../interfaces/interfaces";
import { convertPptToPng } from "../../utils/conversion/convertPptToPng";
import { changeFileExtension } from "../../utils/conversion/changeFileExtension";

const storageController = {
  uploadFileToStorage: async (req: Request, res: Response): Promise<void> => {
    const userId = req.query.userId as string;
    const folder = req.query.folder as string;

    if (!req.file) {
      res.status(400).json({ message: "No file found" });
      return;
    }

    if (!userId || !folder) {
      res.status(400).json({ message: "User ID and folder are required" });
      return;
    }

    try {
      const fileName = req.file.originalname;
      const filePath = `${userId}/${folder}/${fileName}`;
      // const filePath = `default/${fileName}`;
      const fileType = req.file.mimetype;
      const category = req.body.category;

      const response = await storageService.uploadFile(
        req.file.buffer,
        filePath,
        config.STORAGE_BUCKET_ID as string
      );

      if (!response) {
        res
          .status(500)
          .json({ message: "Failed to upload the file to the storage" });
        return;
      }

      const fileId = response.fileId;
      const storageFileName = response.fileName;
      const fileUrl = `https://${config.STORAGE_BUCKET_NAME}.${config.STORAGE_ENDPOINT}/${filePath}`;
      const uploadedAt = new Date();
      const fileSize = req.file.size;

      let pngUrl = null;
      if (folder === "templates") {
        const pngBuffer = await convertPptToPng(req.file.buffer);
        // const buffer =
        ("iVBORw0KGgoAAAANSUhEUgAABKQAAAKiCAYAAADoqgT3AAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAAEnQAABJ0Ad5mH3gAAC2KSURBVHhe7d0tUBxr3sbhrVpzZKrWICNW4BaJjIyMRGK2ChmJi0QiIyORSOpVSGRkJDIyMnLeujnp2SdP+Bhg5j/d09dV1VXnZMgHTDN0/+b5+McCAAAAAAr9o/8FAAAAANgkQQoAAACAUoIUAAAAAKUEKQAAAABKCVIAAAAAlBKkAAAAACglSAEAAABQSpACAAAAoJQgBQAAAEApQQoAAACAUoIUAAAAAKUEKQAAAABKCVIAAAAAlBKkAAAAACglSAEAAABQSpACAAAAoJQgBQAAAEApQQoAAACAUoIUAAAAAKUEKQAAAABKCVIAAAAAlBKkAAAAACglSAEAAABQSpACAAAAoJQgBQAAAEApQQoAAACAUoIUAAAAAKUEKQAAAABKCVIAAAAAlBKkAAAAACglSAEAAABQSpACAAAAoJQgBQAAAEApQQoAAACAUoIUAAAAAKUEKQAAAABKCVIAAAAAlBKkAAAAACglSAEAAABQSpACAAAAoJQgBQAAAEApQQoAAACAUoIUAAAAAKUEKQAAAABKCVIAAAAAlBKkAAAAACglSAEAAABQSpACAAAAoJQgBQAAAEApQQoAAACAUoIUAAAAAKUEKQAAAABKCVIAAAAAlBKkAAAAACglSAEAAABQSpACAAAAoJQgBQAAAEApQQoAAACAUoIUAAAAAKUEKQAAAABKCVIAAAAAlBKkAAAAACglSAEAAABQSpACAAAAoJQgBQAAAEApQQoAAACAUoIUAAAAAKUEKQAAAABKCVIAAAAAlBKkAAAAACglSAEAAABQSpACAAAAoJQgBQAAAEApQQoAAACAUoIUAAAAAKUEKQAAAABKCVIAAAAAlBKkAAAAACglSAEAAABQSpACAAAAoJQgBQAAAEApQQoAAACAUoIUAAAAAKUEKQAAAABKCVIAAAAAlBKkAAAAACglSAEAAABQSpACAAAAoJQgBQAAAEApQQoAAACAUoIUAAAAAKUEKQAAAABKCVIAAAAAlBKkAAAAACglSAEAAABQSpACAAAAoJQgBQAAAEApQQoAAACAUoIUAAAAAKUEKQAAAABKCVIAAAAAlBKkAAAAACglSAEAAABQSpACAAAAoJQgBQAAAEApQQoAAACAUoIUAAAAAKUEKQAAAABKCVIAAAAAlBKkAAAAACglSAEAAABQSpACAAAAoJQgBQAAAEApQQoAAACAUoIUAAAAAKUEKQAAAABKCVIAAAAAlBKkAAAAACglSAEAAABQSpACAAAAoJQgBQAAAEApQQoAAACAUoIUAAAAAKUEKQAAAABKCVIAAAAAlBKkAAAAACglSAEAAABQSpACAAAAoJQgBQAAAEApQQoAAACAUoIUAAAAAKUEKQAAAABKCVIAAAAAlBKkAAAAACglSAEAAABQSpACAAAAoJQgBQAAAEApQQoAAACAUoIUAAAAAKUEKQAAAABKCVIAAAAAlBKkAAAAACglSAEAAABQSpACAAAAoJQgBQAAAEApQQoAAACAUoIUAAAAAKUEKQAAAABKCVIAAAAAlBKkAAAAACglSAEAAABQSpACAAAAoJQgBQAAAEApQQoAAACAUoIUAAAAAKUEKQAAAABKCVIAAAAAlBKkAAAAACglSAEAAABQSpACAAAAoJQgBQAAAEApQQoAAACAUoIUAAAAAKUEKQAAAABKCVIAAAAAlBKkAAAAACglSAEAAABQSpACAAAAoJQgBQAAAEApQQoAAACAUoIUAAAAAKUEKQAAAABKCVIAAAAAlBKkAAAAACglSAEAAABQSpACAAAAoJQgBQAAAEApQQoAAACAUoIUAAAAAKUEKQAAAABKCVIAAAAAlBKkAAAAACglSAEAAABQSpACAAAAoJQgBQAAAEApQQoAAACAUoIUAAAAAKUEKQAAAABKCVIAAAAAlBKkAAAAACglSAEAAABQSpACAAAAoJQgBQAAAEApQQoAAACAUoIUAAAAAKUEKQAAAABKCVIAAAAAlBKkAAAAACglSAEAAABQSpACAAAAoJQgBQAAAEApQQoAAACAUoIUzMzXr18XHz9+XLx9+3bxj3/848Ejj3/58qX/7QAAAPBqghRMwI8fPxbX19eLs7OzxdHR0ZMxaV3HX3/91f9TAAAA4NUEKRihBKiLi4vF8fFxWXy67zg5Oen/aQAAAPBqghSMRKbSZQTU4eHhH2Foncfe3t5daMqIKwAAANgGQQq25Pv378tRUIlEfTjqj4ODg7uQ9Pnz58XNzU3/xwEAAMBkCFJQ6OrqanF6enoXl/rg1B/7+/t3i4/n9wAAAMAuEaRgg759+7Y4Pz9fvH///m6B8D46tUce//Dhw90IqNvb2/6PAgAAgJ0hSDE7GXH07t27xZcvX/qHVpLIlJFL61hsPCOlMmLKKCgAAADmRJBidob1mjIiaVVZ7ykjnTKNro9Kzznyd2fNqKwdlT8TAAAA5kiQYnbaQPSYnz9/3o2iynS7PiyteiR65fcnZmVkFQAAACBIMUNtMLpPps9lFNNDaz7l14+OjhaXl5f9bwUAAABWcP8dOeywNi5l2tz19fXi06dPdwuKD9P57juGdad+/PjR/5EAAADAMwhSzMbXr1/vglIfmh47smbU2dmZXe8AAABgjQSpHZfpZ/ftBpdfy9pGGRmUBbZvbm763zp6CUwZ3TQc+VyGI7vgZURTjsPDwz8+/8eOjJI6OTm5+/MBAACA9ROkdtx9Meqx46F1k3b1+Ne//nUXrU5PT+9GT00xzAEAAMDUCFI7LtPN+ggz1yMjpbJY+X/+85/lr2V0GAAAAFBLkJqpb9++3U3ny/S27Bj33GltYzjybx6m5eVzaKfs5XMbpvLlc23l8eHPyH8DAAAAtQQpZiejooYglZAFAAAA1BKkmJ2sE9WOsgIAAABqCVLMzo8fP5ZB6s2bN/3DAAAAwIYJUsxSQtQQpRKoAAAAgDqCFLO0v7+/DFK3t7f9wwAAAMAGCVLMUnbmG4LU169f+4cBAACADRKkmKX3798vg9T19XX/MAAAALBBghSzdHx8vAxSl5eX/cMAAADABglSzNLJyckySH358qV/GAAAANggQYpZ+vTp0zJInZ+f9w8DAAAAGyRIMUtnZ2fLIJU4BQAAANQRpJilTNMbgtTHjx/7hwEAAIANEqSYpYuLi2WQygLnAAAAQB1Bilm6vr5eBqkPHz70DwMAAAAbJEgxSzc3N8sg9e7du/5hAAAAYIMEKWbp9vZ2GaQODg76hwEAAIANEqSYpe/fvy+D1Nu3b/uHAQAAgA0SpJitIUi9efOmfwgAAADYIEGK2frrr7+WUQoAAACo406c2cpUvSFIff36tX8YAAAA2BBBitn68OHDMkidnJz0DwMAAAAbIkgxW5eXl8sglel7WegcAAAA2DxBilnb399fRqnz8/P+YQAAAGADBClmLRFqCFJ7e3v9wwAAAMAGCFLM2s+fP3/bbS/T+AAAAIDNEqSYvY8fPy6D1Lt37/qHAQAAgDUTpJi9b9++LYNUjh8/fvQfAgAAAKyRIAWLxeLg4GAZpBKoAGAKrq6uFm/fvr07vnz50j8MADBaghQsFov3798vg9T19XX/MACMUkLU8PMrayICAEyFIAWLxeL4+Hh5Qe8dZgCm4uzs7Ldp5wAAU+HKBRaLxadPn5YX87m4B4CpaHeLvb297R8GABglQQoWi8Xnz5+XF/PZdQ8ApiI7xA4/w/LzDABgCgQpWCwWl5eXy4v5o6Oj/mEAGK122t6HDx/6hwEARkmQgsVicXNzs7yYzzvNADAVX79+Xf4My/S9nz9/9h8CADA6ghQsFndrbgwX89mxCACmpN1tz26xAMAUCFLwS/vuMgBMSbtbrLUQAYApEKTgl729veXF/I8fP/qHAWC02rUQ9/f3+4cBAEZHkIJfDg4Olhfzts0GYEryRkpG+A4/x7KuFADAmAlS8Eu7bbb1NwCYmuywN/wcOzk56R8GABgVQQp+adffyNQHAJiSq6ur5c+xjJb6/v17/yEAAKMhSMEvWQR2uJD/8uVL/zAAjF47/fz8/Lx/GABgNAQp+OXTp0/Li/j8NwBMTSLU8LMsm3UAAIyVIAW/ZFTUcBFvy2wApujnz5+LN2/emIIOAIyeIAW/tFtmZz0pAJiidgp6NuwAABgjQQp+yc56LuABmLrb29vlz7Mc37596z8EAGDrBCn4pb2Az6KwADBV79+/X/5MOz097R8GANg6QQp++fHjx/Li/e3bt/3DADAZFxcXy59pFjcHAMZIkIJGO8UBAKaqX9z86uqq/xAAgK1y1w2NjIwaLt4zYgqm4OvXr3eLGLfn71NHPvbo6Gjx+fNn68vAjjo5OVl+z+f7HQBgTAQpaGTtqOHiPWtKwVi9JEI9dmRKT25es7g/sBtubm6W3+N//fWXN1oAgFERpKCR3fWGi3c35oxF4tPl5eXi06dPiw8fPqwtQq1y5O9K+Pr+/Xv/zwImoH2jJSMiAQDGQpCCxvHx8fLCPQEAtuXs7Oy3G8nHjpeMbkrkOj8/v5vGk9/f/5n9kdEV+TcxHnk+XhIn83uEifnI9/nw3B8eHvYPAwBsjSAFjYwEGS7cv3z50j8MG5eotL+//0dE6I+XRKjHrDoFcF1/Hy+36jny1GHU2zzkeU5QHp530/YAgLEQpKCRKVHDRXv+G6rkpjGjlfpokCMjpTJVL+dkRu4lHlXJ39fGjwSr7N5FvcfOkZccRknNRzva0iYGAMBYCFLQyKio4aI9o0Vg0xIZEpra7dlz5P/HMkUu/8b235coIkrVShhcxznSvsZl+pbncR4StIfn/erqqn8YAGArBClo5KZvuGjPelKwKdn9ql2zrD0SfMY2naoNGTkyaiqfA5vXT7l6zTmS6Vrtn+V5nIdM7x2ec9PRAYCxEKSgkbVZhov27LgH65TRKLkZfGix8sSBMa/RdF9As0D2ZiUgtdP08vV+7TnSrpU3HM8dacW05PkdnmvT0QGAsRCkoHF7e7u8aE80gHVJiOqnXA1H4ufFxUX/W0bpoc/DTe765Zzov9br2v3zvudRlNpd7QhHo38BgLEQpKCR0QjDRXtGIsBr5Zxq128Zjkybyo1h5QLl65KpYu/fv//jczIVaH0yja6fppev+TrleUwMbf+Ol0wDZPza0b/rPo8AAF5KkIJOe3MGr5GbwL29vd/Oqfx/RhPtwo1/piC2YSoBxQ5er5eImSDenjObin15DrO4+fB3mX65m9rRv5kaDAAwBu64odPeCMJL5Cb/9PT0txCVI7+2a7ua9fEkN7u79jlWa0fUVUS+djrX2Ncx42XyPTk8x5mqCQAwBu64oSNI8RqJB+2IkxwZ4bLLN/n99LIElV0YAbYNGaHUnjubGhnV6nfeG87ZLH7uedwd7WjNjJgCANg2d9zQEaR4qcSE/sY+cSY3/Lvu/Pz8t887X4eKmLJr2mhQufh0ppG2z5/ncfe002ttQgAAjIE7bugIUjzXfaOi5ngjn4DSB41NTzfbJVngfvi6ZVpV9dTH/P0ZFdW+Bg6HkVLTl10bh+fTph0AwBi444aOIMWqHlorKnFqriHm8vLybh2i4WuRwMFq2lFmGVm3TXke29dCi51PX16vEjqH5zRTbQEAtskdN3QEKVZxdXX1xw56GRV1dnbWf+jsJGYMX5N8japH+kxVu5h54tS2tYudv3v3rn+YCWpHMZ6cnPQPAwCUcscNHUGKx2TqUhsOhiPrs1go+H/aWJepQjytHb2S6XPblrXP2nOc6cvmCsPzuY1poQAALVeY0BGkuE9uzrMQcBsNciS8CC5/ahfJNrrmaZk+1YaCsWgX6Wc3tD/jMpoRAGBbXGFCR5Ci9VCIypHpL3PYQe8lMpKs/VrNbYH352oDXuXuek/JFNT8m0zv2h3tunfbXqsMAJg3d9zQEaQYZCHn+0JUFu22IPDTjo6Oll+zjLSZ60Lvq2h3aRTv2KR8H7bfl6I6ALAt7rihI0gR7YiV4ci5IRasLje67ffTwcGBNWvu0Y8mEwjYtDaA2kERANgWd9zQEaToY5QQ9XIZSdauQ/Tx48f+Q2av3c0uoQA2Lbs4OucAgG1zxw0dQWre+hiV3fOM6nmd9uY3R3b64n/aqY05/2DTMiqvDcVG5QEA2+COGzqC1HyJUZuTr+Xwdc33mK/r3/J1aNcpszYZVTKFdjjvrO8GAGyDO27oCFLzlHVUxKjNyYiMNrzYte1v7eixvPZAleywN5x7V1dX/cMAABvnjhs6gtQ87e3tiVEb1q6VlOlC/D5KJXEKqiQKD+eeNfIAgG1wxw2dNkxYV2MesqZRO0pFjNqc4ess+C4Wl5eXvwU6rzdUOjs7W55/1i4DALbBHQF02u2wTWOYh3akwOnpaf8wayRI/U87ZcoURqq1IxaPj4/7hwEANs4dAXTaOGEKzTy0o+IsKr1ZgtTfsoh0+7X4+vVr/yGwUe3I0ExTBgCoNu87ArhHu8iwUQu7r5+ux2YJUn/7+PHj8uvw7t27/mHYuNvb2+U5uL+/3z8MALBx874jgHu0gSLT99htpuvVEqT+1u44mLWkoFrWyhvOwZyPAADV5n1HAPfIwsLDRbqdwHbb9+/f757j4fk2XW+zMi1NkPqbrwNj0E5XzushAEAlV8Jwj/YiPWu9sJvaaVMHBwf9w6xRRmPkazx8vec+TU2QYgyydtRwHn7+/Ll/GABgo1wJwz3ai3TTaXZTPzrK87wZWacmu3m1O8rl6z730CtIMQbtTntzj8QAQD1XwnCPduTM2dlZ/zA7wOiozcr3TRaJb8OL76n/EaQYg0xRb8O8aXsAQCVXwnCPi4uL5QV6RnawW4yO2pyMfMpmAH2E8v30O0GKsTBtDwDYFlfCcI928WXbYe8eo6PWLyEquxS2oS9H/j83vBkVZdH4/xGkGAvT9gCAbXElDPdot8POkf9nd7RTyYyOerlM98mIivtGRCVEmZr3sDbc5esI22LaHgCwLYIUPCAjo4YL9IyYYjfkZmt4Xt+8edM/zAqurq4WR0dHf4yGGo4EqrkvWv6UNuIZOca2mbYHAGyDIAUPyA33cIGeKQ3shoyIGp5X01NWM+yUd3x8vNjb2/sjQA1HvmeMOFvNycmJAMBomLYHAGyDIAUPyHSj4QI9aw6xGz59+uR5fUIboB7aKW84sgZXgoppZ89zfn7uPGQ0TNsDALZBkIIHtCNpMp2B3ZBd3obnNbspzl3iU6bgJdTla/NUgMqRUVKJKKblvVy+5l5fGBPT9gCAaoIUPCA32+0NONOXxenbUQBzCyrX19d3N5qJSZmW89AaUP1hp7z1a9cy8/rCGJi2BwBUE6TgEVn0erhANyVp+tppUnOIAAluiU/tAv2rHAJUjfb1xRQptq2ftudnHgCwaYIUPCLr4wwX53bam742zCRO7aKEjXxuq0aoRJGMhjg9Pb0bISFA1Wmnj9o4gTHIa8FwTmZaKQDAJglS8Ij2htHuYQ/LjUtuZMa87ki7JlhGAezSiJRMRUzQaNeAue9IYM1OeFkvKtP3dulrMEXtiL08L7BtGVE5nJMZIQkAsEmCFDyivTjf1RE169AuhJ3YMUZtXDw5OekfnqSEwOyE99BaUPn1hA4xdZyyoPzwXGWkWsIibFM2ehjOybxmAgBskiAFj8g7xMPFeaY0cb823OVIJMkInLFoF6jPMYXpl5k6l69hjpyHCX05Mgoqo9GyBlYfoIYjj2fElDVgxq+NuWP6nmGe2tfKnJsAAJskSMEj2neLTal5WEZ2PDVdLDc3CVfbmCbWBrOx7R6VaJTg9Jxd7+47smZU/pyMumE6MlpveA5znsK22czjb/nc8yZAG43bI79u7TcAeB1BCh6RUSrDxefh4WH/MI1EqXZa3ENHokt1mGpvsMYyfS3hKDHiNREqo6TyZ0xhxBf3a9c2S1SEbZv7wuZ5bc6I6PbnxkNHXr8BgJcTpOARiSbtzT9PSxxJcHroXeX2Qr4iTGUa1PB35gZj2/LveSrc5VzLTWGOYRHyHFk0fpjGl6k1TF9GYbRR0gg3tm2uC5tnRPRTI337Y1fWIwSAbRGk4AntzSIvl5Eg2eWtv6DP1zfhJTdBiS75uASXdU0VyZ85/F1Z22pbMrXjvs8/Rz7/sYzcol47IsUUILZt1xc2T/TNz5hsVJKfD4+tyWdaHgBsljtseEI70sfohdd7KEw9dORjc8OQd6LbUUKZTrmK9u/a5I1FRobl35UpLsOIpgSwx2528rjpdowlmkLsysLmmUY+bAqRkabP+bmTkVIJcwDAZglS8IR29IJdsNbnuWHqsSPrew1T3Pqj/biHwlDlkWmDWZ9k01MVmY52WumUAwC7o10/aQqvVX18ynps/WvvU0d+PuS12RtPAFBHkIInZMTCcMG6yRE2c5V343MjkZFPGSmSm4nHRhVN9UhoyOeYGydo5ZywjhRj0q6llNetMRii0zAKNfEoPyueG5+GNfqGUbf584xUBYDtEKTgCe10mjkt8DoWQ7DK9In2JiTHa3aoW/cxjNJqFyEf1sNys8NT2tF8wjfblnNwOB9zbm7DsNtdXlv719tVj/zehKdEtVWneQMAdQQpeEJ7YW5HnWlp1/9yM8KYWUeKMel3f6yctveS3e5yJJxlc4z8zPYmAABMgyAFT2jXd8lFMtMxPG+5sYIxs44UY1M5bW8YDfXYVO2sa5XolJ3/EnCzS54RqAAwbYIUPKHdcShrVTANucHxvDEV/TpSbrLZtoppe0+NhrLbHQDsNkEKnpAbxfYdWqbByDampt1AIWvfwDa9dtpepknndXjY/W5YWy+vx49tXGG3OwCYD0EKVtBeOOcinfGz9hdTkxv+NgBkUXzYplWm7WU0X9Zueu1GE0ZDAcD8CFKwgoODg+VFs3dtp8HuiExRztXhvE0IzwhN2JaHpu0NEardOOIlh9FQADBvghSsoN2S3W5t09BOf/KuO1ORANWOyBRT2aZ+2t5///vflSJUzuH83MxxdHS0nK6XUVbDNL6szwgAzJsgBSvIBfVwoX11ddU/zAiJiExVpuoN525iwHPX7oF1yUiopwJU4lOmRScyAQA8hyAFK8jF9nDxnSkMjF97E+WGnqnJoubD+ZvRfrBuGY03jFbKKNJhFFPegEnQfyxEiVAAwDoIUrCCdj2i8/Pz/mFGqL2ZgqnJyJQ2AFhjh1W1oSk/r/LzK/FomEL3moXH//nPfy7+7//+r/8rAQBexJ0arCAX9cMFeS7uGT9Biqn78OGD150ZyDTwx0YjbfMYRkL9+9//Xv6aaesAwLq4U4MVtDsNmT4zDW/evFk+ZzBF7VpSCRbspm3FqPy9w6ip7Jg3TNkbRldllN6gHSWcQAUAsA7u1GAFuTgfLsazvgbj1954wRT1O+5Zr2c3ZSfFPha95siUvCE0nZ6e3sWkvKnSR6bnyMYQw58vjgIA6+JODVbQXoznIp/xa2/QYKoycmU4j43OZJvaUacvDVsAAC13arCCLCg8XIjv7+/3DzNCghS7oF3cPCNfMmoKtiFBdDgXrWkGAKyDOzVYQW4Chwtx0xWmod1Jyrv5TNnBwcHyXM7UK9iGi4uL5Xl4eHjYPwwA8GyCFKzIiJtpyVpfw/OVaZbfv3/vPwQmod3l05RhtuXHjx+/hf78PwDAa7izhhW1OyGJG+PXTnXKkRupLB4MU5PXmzYEmC7FtmRk1HAeGnkKALyWIAUrev/+/fJC/PPnz/3DjFC2J++jFExRu36P1yC2pR15enl52T8MAPAsghSsKGu3DBfips1MR26a2ht5mKKsY9dG8RxZ0wcqnZ6eLs+/TCUFAHgNd2ewon79DNP2psN0J3ZBolS7wHnO66urq/7DYGMyMm84/z5+/Ng/DADwLIIUPINpe9OUG6d2ZIkoxVQljPdR6ubmpv8w2IgE0OHc+/DhQ/8wAMCzCFLwDKbtTdN9051EKabq9vb2t00W3rx5Y4FpSnz79m153iWMAgC8hiAFz2Da3nSJUuySRKmEqOFcTqDKr8Em5XW0DaEAAK8hSMEzmbY3XfdFqYx6gynKqKg+SonkbNre3t7ynBNBAYDXEKTgmUzbm7Y+SmXEW6ahwBRdX1//Nmoz06gykhM2JWtHDeebUaYAwGsIUvBMpu1NX57Ddg2e/f39u1AFU9QuND2Ecuczm3J5ebk81/I6CgDwUoIUvIBpe9OXncnasHh8fNx/CExGO3IzR16jRCk2IedVO20vo/QAAF5CkIIXMG1vN5yfn/92E392dtZ/CExGfz6LrGzKx48fnWcAwKsJUvACpu3tjnY9FM8lU5c1fdrzOeEA1i0L6g/nWH4WGo0HALyEIAUvZNrebsiN1OHhoeeSnZERK22UMvKPTcgC+sM5ZrdSAOAlBCl4IdP2dkf7XCZOebefqTs6OvotSgkGrFs7RdTPQADgJQQpeKF+2p6t1qerfy6z614WPYepSlRtR3Hm/M5ufLAumd7cvm7e3t72HwIA8ChBCl4h7woPF+PZCpvpahfpHY78mjWlmKqE1nZaVeJB1v6BdWl/BhqFBwA8lyAFr9AuIGynoenLDdWbN29+i1K5ibcGD1OVoPr27dvl+Zzz20gW1qWdtpcNIgAAnkOQgle4vr5eXoznpo/pyw18O9VpOPJcwxQlQLWhNa9VRv6xDt++ffst3lt/DwB4DkEKXiEX3220YHckQLXTnXIT72aLqcpUvXa9n5zb1r1jHdoReMI9APAc7qDhlQSp3ZVRJO3IkkxJMbKEqcqi5m2UykhAkZXXOjk5WZ5TWXcPAGBV7qDhlQSp3ZZ1pdrnODf0u7jYeUbQ5PNqRzs8deRjLWQ8Lf35fHR01H8IPEs29BjOp+xQCgCwKnfQ8ErtzR27KQvW9zEmYSojprKwfaapTHH600siVH/k68C0ZJH+9jnMCBd4qbz2tSPv7OQIAKzKHTS8Untjx+7KKIB2TSnH34eYMU0Jke3zmJFSpu/xUonzXhMAgOdyBw2v1N7Usft2NUzt7e3d3UhalHg++pF/h4eHkxzpx/ZlfbLhPMpoqV2b0gwAbIY7aHildqqCm/n5yLSUrMeTkSbv3r37I/BM4RCh6EdKZQ2g29vb/sPgSW2oPz8/7x8GAPiDIAWv1I4yyAW5aS/AlCQetFEqO0taB4jnas+jxG4AgKcIUvBKmZrQjpLyzjAwNZmK2r6O5b/za7CqvBmTmDmcQ84fAOApghSsQfvOsPUzgCm6ubn5LSjk+Pz5c/9h8KB2CmimMrNdWdsrz4PvYwDGSpCCNcg7w+36GdmxCmBqvn37tnj79u1vUerTp0/9h8G9sv5Ye+6Y+rld/fdy/j9rHwLAWAhSsCZZGLq98LNbFTBFee3qd5IUpVjVhw8fludNRkyxPf2mBTkyihsAxkKQgjXKtunDRV+GygNMUUZ9vn//XpTi2bJ21HDOZAqojT62J1/7fhdYQQqAMRGkYI3adyPPzs76hwEmQ5TipbLL3nDOXFxc9A9TJOtbtpsV5DBqDYAxEaRgjbI2w3DRl2kLAFMmSvESOUeG88Xi5tvRPgc5Eqa8UQbA2AhSsEZZwHW4+MvioQBTJ0rxXNlptj1fLG6+WVlMPutYZkRUvjfb5QNy5P+zYQEAjI0gBWvWXgQC7AJRiudqFzdPEEkwYT2y8UC+//rNB+478n1rHS8AxsodM6yZIAXsovuilPVoeEg7Yng4srbU58+f+w9lRUOIymLx/df2viNRUIwCYMzcMcOatQuIZtoCwK64L0rlpjc3ytDr1zEaDqOlnuepEJUlArJWVwJxPi5fX9MkAZgCQQrWrL1Z804wsGsSpdrpWDkydSjr2EAvYSShJNGkDShG7jztsRCVr2E2UgGAKROkYM3anfbsLgTsqtPT099ukHPTfHNz038Y3MmI4TasnJyc9B/Crwh1cXGxOD4+FqIA2HmCFKxZLibbaXu2WQZWcXV1dXezOaUbztw4t693+e+p/Nup175hk8O0sr9lB7zskNdPhxWiANh1ghRsQN75bW/QAJ7STmnqjzHfjGZUVD+Sww58PKSNLpn6OVeJUP1UxvuOMX/vA8BrCVKwAVkbw+LmwHNkNGV/M9oeYx59lPWj+i3oRSnu0+++lzdw5vIzMiOos7Zk/73SH/v7+3exKqMmAWCXCVKwIRY3B55rlSg1VrnZ7qcciVLcJ+sj9ed1AsyuhqnLy8vF0dHRH9/Pw5ERhnk81wo2BwBgTgQp2BCLmwPr0EeqMcvoUFGKp9y3U2OOhKkhzGRK21S1C5Pv7e398XkORz7XxCoAmKtxX9nChOWCdCo3kcC4tVOAc2RdmbFumCBKsarEmMemryXmJOpMIdpkKmK+Jw8PD//4PNoj0/ES3HKNAABz5y4ZNqi9CAV4qUxn6m9sc4x1lzJRiud4KkzlyLS2bcapnNPX19d3R3bEy/mc9a8yAvqxUVA58ng+dsqjvgBgE9wlwwa1F6QAL5Wb4X7dnRwZKTXWNerui1IJa/l1uE8Ca2JPpvP1OzdO7bAwOQA8zV0ybFA7zQZgHfpdynKMdTHo+6JUpjRZuJlV5FxP1El47c/5sR35eZ+QZmFyAFidu2TYoGEx4gzVB1iXvKa0N8NjHSUV90WpjH7Z1tQrpmnbcSrBKdPzcpyent5N2cvmJZnCN9apswAwdoIUAExQu5NnpgflxnjMcgPf3+RbVwoAYL4EKQCYoOzS1e++l8WTM4pkrFP4Es36BaCNLgEAmCdBCgAm6r5RRzkSqjJleIwSy7KO1PBvzbo7AADMjyAFABP22No6+bUxjpjqF2YfazwDAGBzBCkA2BFZKPzg4OCPMNUGqqw9NQbtKKmM6AIAYF4EKQDYIdnV7vj4+I8YNab40081PDo66j8EAIAdJ0gBwI56aMTUtkZJZSH2TCFs/y3v37+/i2gAAMyLIAUAM9DvyDeGQ4wCAJgvQQoAZiALh/dBaJuHGAUAMG+CFADMxBii1JgWVgcAYHsEKQAAAABKCVIAAAAAlBKkAAAAACglSAEAAABQSpACAAAAoJQgBQAAAEApQQoAAACAUoIUAAAAAKUEKQAAAABKCVIAAAAAlBKkAAAAACglSAEAAABQSpACAAAAoJQgBQAAAEApQQoAAACAUoIUAAAAAKUEKQAAAABKCVIAAAAAlBKkAAAAACglSAEAAABQSpACAAAAoJQgBQAAAEApQQoAAACAUoIUAAAAAKUEKQAAAABKCVIAAAAAlBKkAAAAACglSAEAAABQSpACAAAAoJQgBQAAAEApQQoAAACAUoIUAAAAAKUEKQAAAABKCVIAAAAAlBKkAAAAACglSAEAAABQSpACAAAAoJQgBQAAAEApQQoAAACAUoIUAAAAAKUEKQAAAABKCVIAAAAAlBKkAAAAACglSAEAAABQSpACAAAAoJQgBQAAAEApQQoAAACAUoIUAAAAAKUEKQAAAABKCVIAAAAAlBKkAAAAACglSAEAAABQSpACAAAAoJQgBQAAAEApQQoAAACAUoIUAAAAAKUEKQAAAABKCVIAAAAAlBKkAAAAACglSAEAAABQSpACAAAAoJQgBQAAAEApQQoAAACAUoIUAAAAAKUEKQAAAABKCVIAAAAAlBKkAAAAACglSAEAAABQSpACAAAAoJQgBQAAAEApQQoAAACAUoIUAAAAAKUEKQAAAABKCVIAAAAAlBKkAAAAACglSAEAAABQSpACAAAAoJQgBQAAAEApQQoAAACAUoIUAAAAAKUEKQAAAABKCVIAAAAAlBKkAAAAACglSAEAAABQSpACAAAAoJQgBQAAAEApQQoAAACAUoIUAAAAAKUEKQAAAABKCVIAAAAAlBKkAAAAACglSAEAAABQSpACAAAAoJQgBQAAAEApQQoAAACAUoIUAAAAAKUEKQAAAABKCVIAAAAAlBKkAAAAACglSAEAAABQSpACAAAAoJQgBQAAAEApQQoAAACAUoIUAAAAAKUEKQAAAABKCVIAAAAAlBKkAAAAACglSAEAAABQSpACAAAAoJQgBQAAAEApQQoAAACAUoIUAAAAAKUEKQAAAABKCVIAAAAAlBKkAAAAACglSAEAAABQSpACAAAAoJQgBQAAAEApQQoAAACAUoIUAAAAAKUEKQAAAABKCVIAAAAAlBKkAAAAACglSAEAAABQSpACAAAAoJQgBQAAAEApQQoAAACAUoIUAAAAAKUEKQAAAABKCVIAAAAAlBKkAAAAACglSAEAAABQSpACAAAAoJQgBQAAAEApQQoAAACAUoIUAAAAAKUEKQAAAABKCVIAAAAAlBKkAAAAACglSAEAAABQSpACAAAAoJQgBQAAAEApQQoAAACAUoIUAAAAAKUEKQAAAABKCVIAAAAAlBKkAAAAACglSAEAAABQSpACAAAAoJQgBQAAAEApQQoAAACAUoIUAAAAAKUEKQAAAABKCVIAAAAAlBKkAAAAACglSAEAAABQSpACAAAAoJQgBQAAAEApQQoAAACAUoIUAAAAAKUEKQAAAABKCVIAAAAAlBKkAAAAACglSAEAAABQSpACAAAAoJQgBQAAAEApQQoAAACAUoIUAAAAAKUEKQAAAABKCVIAAAAAlBKkAAAAACglSAEAAABQSpACAAAAoJQgBQAAAEApQQoAAACAUoIUAAAAAKUEKQAAAABKCVIAAAAAlBKkAAAAACglSAEAAABQSpACAAAAoJQgBQAAAEApQQoAAACAUoIUAAAAAKUEKQAAAABKCVIAAAAAlBKkAAAAACglSAEAAABQSpACAAAAoJQgBQAAAEApQQoAAACAUoIUAAAAAKUEKQAAAABKCVIAAAAAlBKkAAAAACglSAEAAABQSpACAAAAoJQgBQAAAEApQQoAAACAUoIUAAAAAKUEKQAAAABKCVIAAAAAlBKkAAAAACglSAEAAABQSpACAAAAoJQgBQAAAEApQQoAAACAUoIUAAAAAKUEKQAAAABKCVIAAAAAlBKkAAAAACglSAEAAABQSpACAAAAoJQgBQAAAEApQQoAAACAUoIUAAAAAKUEKQAAAABKCVIAAAAAlBKkAAAAACglSAEAAABQSpACAAAAoJQgBQAAAEApQQoAAACAUoIUAAAAAKUEKQAAAABKCVIAAAAAlBKkAAAAACglSAEAAABQSpACAAAAoJQgBQAAAEApQQoAAACAUoIUAAAAAKUEKQAAAABKCVIAAAAAlBKkAAAAACglSAEAAABQSpACAAAAoJQgBQAAAEApQQoAAACAUoIUAAAAAKUEKQAAAABKCVIAAAAAlBKkAAAAACglSAEAAABQSpACAAAAoJQgBQAAAEApQQoAAACAUoIUAAAAAKUEKQAAAABKCVIAAAAAlBKkAAAAACglSAEAAABQSpACAAAAoJQgBQAAAEApQQoAAACAUoIUAAAAAKUEKQAAAABKCVIAAAAAlBKkAAAAACglSAEAAABQSpACAAAAoJQgBQAAAEApQQoAAACAUoIUAAAAAKUEKQAAAABKCVIAAAAAlBKkAAAAACglSAEAAABQSpACAAAAoJQgBQAAAEApQQoAAACAUv8PrQGDQRyi5AQAAAAASUVORK5CYII=");
        // const pngBuffer = Buffer.from(buffer, "base64");

        const pngFileName = changeFileExtension(fileName, ".png");
        const pngFilePath = `${userId}/${folder}/${pngFileName}`;
        // const pngFilePath = `default/${pngFileName}`;

        await storageService.uploadFile(
          pngBuffer,
          pngFilePath,
          config.STORAGE_BUCKET_ID as string
        );

        pngUrl = `https://${config.STORAGE_BUCKET_NAME}.${config.STORAGE_ENDPOINT}/${pngFilePath}`;
      }

      (await pool.query(
        "INSERT INTO files(name, file_name, type, size, folder, template_category, file_id, file_url, png_url, uploaded_at, user_id) VALUES($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)",
        [
          fileName,
          storageFileName,
          fileType,
          fileSize,
          folder,
          category,
          fileId,
          fileUrl,
          pngUrl,
          uploadedAt,
          userId,
        ]
      )) as DbQueryResultProps;

      res.status(200).json({ message: "File uploaded successfully" });
    } catch (error: unknown) {
      handleError.controllerError(
        res,
        error,
        "uploading the file to the storage"
      );
      return;
    }
  },

  getFileMetadata: async (req: Request, res: Response): Promise<void> => {
    const userId = req.query.userId as string;

    if (!userId) {
      res.status(400).json({ message: "User ID is required" });
      return;
    }

    try {
      const result = (await pool.query(
        "SELECT name, file_name, type, size, folder, template_category, file_id, file_url, png_url, uploaded_at, source FROM files WHERE user_id = $1",
        [userId]
      )) as DbQueryResultProps;

      res.status(200).json({
        message: "Metadata retrieved successfully",
        data: result.rows,
      });
      return;
    } catch (error: unknown) {
      handleError.controllerError(
        res,
        error,
        "retrieving the file metadata from the storage"
      );
      return;
    }
  },

  deleteFileFromStorage: async (req: Request, res: Response): Promise<void> => {
    const fileId = req.query.fileId as string;
    const fileName = req.query.fileName as string;

    if (!fileId) {
      res.status(400).json({ message: "File ID is required" });
      return;
    }

    if (!fileName) {
      res.status(400).json({ message: "File name is required" });
      return;
    }

    try {
      await storageService.deleteFile(fileId, fileName);

      (await pool.query("DELETE FROM files WHERE file_id = $1", [
        fileId,
      ])) as DbQueryResultProps;

      res.status(200).json({ message: "File deleted successfully" });
      return;
    } catch (error: unknown) {
      handleError.controllerError(
        res,
        error,
        "deleting the file from the storage"
      );
      return;
    }
  },

  downloadFileFromStorage: async (
    req: Request,
    res: Response
  ): Promise<void> => {
    const fileId = req.query.fileId as string;

    if (!fileId) {
      res.status(400).json({ message: "File ID is required" });
      return;
    }

    try {
      const file = await storageService.downloadFile(fileId, "arraybuffer");

      res.status(200).json({
        data: file,
        message: "File downloaded successfully",
      });
    } catch (error: unknown) {
      handleError.controllerError(
        res,
        error,
        "downloading the file from the storage"
      );
      return;
    }
  },
};

export default storageController;
